# @author Alejandro Galue <agalue@opennms.org>

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: common-settings
  namespace: opennms
data:
  DOMAIN: test
  TIMEZONE: America/New_York
  OPENNMS_INSTANCE_ID: K8S
  CASSANDRA_CLUSTER_NAME: OpenNMS
  CASSANDRA_DC: Main
  CASSANDRA_REPLICATION_FACTOR: "1"
  ELASTIC_INDEX_STRATEGY_FLOWS: daily
  ELASTIC_REPLICATION_FACTOR: "0"
  ELASTIC_NUM_SHARDS: "1"
  KAFKA_NUM_PARTITIONS: "1"
  KAFKA_REPLICATION_FACTOR: "1"
  MINION_LOCATION: Kubernetes
