# @author Alejandro Galue <agalue@opennms.org>
#
# Requires the ingress-dns add-on in Minikube, and some configuration in your host machine

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: onms-ingress
  namespace: opennms
  annotations:
    cert-manager.io/issuer: onms-ca-issuer
spec:
  tls:
    - secretName: opennms-ingress-cert
      hosts:
        - onms.test
        - grafana.test
        - kafka-manager.test
        - kibana.test
        - tracing.test
  rules:
    - host: onms.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: opennms-core
                port:
                  number: 8980
    - host: grafana.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
    - host: kafka-manager.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kafka-manager
                port:
                  number: 9000
    - host: kibana.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kibana
                port:
                  number: 5601
    - host: tracing.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: onms-tracing-query
                port:
                  number: 16686

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grpc-ingress
  namespace: opennms
  annotations:
    cert-manager.io/issuer: onms-ca-issuer
spec:
  tls:
    - secretName: grpc-ingress-cert
      hosts:
        - grpc.test
  rules:
    - host: grpc.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grpc-server
                port:
                  number: 8990
