# @author Alejandro Galue <agalue@opennms.org>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentinel
  namespace: opennms
spec:
  replicas: 1
  template:
    spec:
      initContainers:
      - name: init-config
        env:
        - name: CASSANDRA_SERVER
          $patch: delete
