# @author Alejandro Galue <agalue@opennms.org>

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: onms-ingress
  namespace: opennms
spec:
  tls:
    - secretName: opennms-ingress-cert
      hosts:
        - onms.gce.agalue.net
        - onmsui.gce.agalue.net
        - cassandra-reaper.gce.agalue.net
        - grafana.gce.agalue.net
        - hasura.gce.agalue.net
        - kafka-manager.gce.agalue.net
        - kibana.gce.agalue.net
        - elastichq.gce.agalue.net
        - tracing.gce.agalue.net
        - flink.gce.agalue.net
  rules:
    - host: onms.gce.agalue.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: opennms-core
                port:
                  number: 8980
    - host: onmsui.gce.agalue.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: opennms-ui
                port:
                  number: 8980
          - path: /opennms/nrt
            pathType: Prefix
            backend:
              service:
                name: opennms-core
                port:
                  number: 8980
    - host: cassandra-reaper.gce.agalue.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cassandra-reaper
                port:
                  number: 8080
    - host: grafana.gce.agalue.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
    - host: hasura.gce.agalue.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hasura
                port:
                  number: 8080
    - host: kafka-manager.gce.agalue.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kafka-manager
                port:
                  number: 9000
    - host: kibana.gce.agalue.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kibana
                port:
                  number: 5601
    - host: elastichq.gce.agalue.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: elastichq
                port:
                  number: 5000
    - host: tracing.gce.agalue.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: onms-tracing-query
                port:
                  number: 16686
    - host: flink.gce.agalue.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flink-jobmanager
                port:
                  number: 8081

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grpc-ingress
  namespace: opennms
spec:
  tls:
    - secretName: grpc-ingress-cert
      hosts:
        - grpc.gce.agalue.net
  rules:
    - host: grpc.gce.agalue.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grpc-server
                port:
                  number: 8990
