# @author Alejandro Galue <agalue@opennms.org>

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: opennms
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: kafka
        env:
        - name: KAFKA_DEFAULT_REPLICATION_FACTOR
          value: '1'
        - name: KAFKA_MIN_INSYNC_REPLICAS
          value: '1'
        resources:
          limits:
            memory: 1Gi
            cpu: 200m
          requests:
            memory: 512Mi
            cpu: 100m
