# @author Alejandro Galue <agalue@opennms.org>

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sentinel
  namespace: opennms
spec:
  replicas: 1
  template:
    spec:
      affinity:
        $patch: delete
      containers:
      - name: sentinel
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 512Mi
          $patch: replace
