# @author Alejandro Galue <agalue@opennms.org>

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zk
  namespace: opennms
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: zk
        env:
        - name: ZOO_SERVERS
          value: server.1=zk-0.zookeeper.opennms.svc.cluster.local:2888:3888
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 128Mi
          $patch: replace
