# @author Alejandro Galue <agalue@opennms.org>

# For cloud providers / public access
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: opennms
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: agalue@opennms.org # Warning: use your own email
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx

# For private CA
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: opennms
spec:
  selfSigned: {}

# Root CA
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: onms-ca
  namespace: opennms
spec:
  isCA: true
  commonName: onms-system
  secretName: onms-ca
  subject:
    organizations:
    - OpenNMS
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io

# For Local Deployments and Minion Authentication
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: onms-ca-issuer
  namespace: opennms
spec:
  ca:
    secretName: onms-ca

# Minion Client Certificate
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minion-cert
  namespace: opennms
spec:
  commonName: minion
  secretName: minion-cert
  privateKey:
    algorithm: RSA
    size: 2048
  subject:
    organizations:
    - OpenNMS
  issuerRef:
    name: onms-ca-issuer
    kind: Issuer
    group: cert-manager.io
