# @author Alejandro Galue <agalue@opennms.org>

---
apiVersion: v1
kind: Service
metadata:
  name: flink-taskmanager
  namespace: opennms
spec:
  clusterIP: None
  ports:
  - name: data
    port: 6121
  - name: rpc
    port: 6122
  - name: query
    port: 6125
  selector:
    app: flink
    component: taskmanager

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: flink-tm
  namespace: opennms
spec:
  replicas: 2 # Defines parallelism for the tasks
  serviceName: flink-taskmanager
  selector:
    matchLabels:
      app: flink
      component: taskmanager
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      initContainers:
      - name: dependencies
        image: waisbrot/wait
        imagePullPolicy: IfNotPresent
        env:
        - name: TARGETS
          value: flink-jobmanager.opennms.svc.cluster.local:6123
        - name: TIMEOUT
          value: '900'
      containers:
      - name: taskmanager
        image: apache/flink:1.13-java11
        imagePullPolicy: IfNotPresent
        args:
        - taskmanager
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
              key: TIMEZONE
              name: common-settings
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: FLINK_PROPERTIES
          value: |
            jobmanager.rpc.address: flink-jobmanager.opennms.svc.cluster.local
            taskmanager.host: $(POD_NAME).flink-taskmanager.opennms.svc.cluster.local
            taskmanager.data.port: 6121
            taskmanager.rpc.port: 6122
            jobmanager.rpc.port: 6123
            blob.server.port: 6124
            queryable-state.proxy.ports: 6125
            taskmanager.numberOfTaskSlots: 2
            parallelism.default: 2
        ports:
        - containerPort: 6121
          name: data
        - containerPort: 6122
          name: rpc
        - containerPort: 6125
          name: query
        livenessProbe:
          tcpSocket:
            port: 6122
          initialDelaySeconds: 30
          periodSeconds: 60
        resources:
          limits:
            cpu: 400m
            memory: 2Gi

