# @author Alejandro Galue <agalue@opennms.org>
# Source: https://github.com/agalue/onms-grpc-server/
#
# WARNING:
# - Connection is encrypted, but there is no authentication in place.
#   Any minion can connect to it, which is not ideal.

---
apiVersion: v1
kind: Service
metadata:
  name: grpc-server
  namespace: opennms
  labels:
    app: grpc-server
spec:
  ports:
  - port: 8990
    name: http
  - port: 2112
    name: prometheus
  selector:
    app: grpc-server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server
  namespace: opennms
  labels:
    app: grpc-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      initContainers:
      - name: dependencies
        image: waisbrot/wait
        imagePullPolicy: IfNotPresent
        env:
        - name: TARGETS
          value: kafka.opennms.svc.cluster.local:9092
        - name: TIMEOUT
          value: '900'
      containers:
      - name: grpc-server
        image: agalue/onms-grpc-server
        imagePullPolicy: Always
        ports:
        - containerPort: 8990
          name: http
        - containerPort: 2112
          name: prometheus
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
              key: TIMEZONE
              name: common-settings
        - name: PORT
          value: '8990'
        - name: HTTP_PORT
          value: '2112'
        - name: BOOTSTRAP_SERVER
          value: kafka.opennms.svc.cluster.local:9092
        - name: TLS_ENABLED
          value: 'false'
        - name: INSTANCE_ID
          valueFrom:
            configMapKeyRef:
              key: OPENNMS_INSTANCE_ID
              name: common-settings
        - name: MAX_MESSAGE_SIZE
          value: '4194304'
        # Kafka Consumer
        - name: CONSUMER_SECURITY_PROTOCOL
          value: SASL_PLAINTEXT
        - name: CONSUMER_SASL_MECHANISM
          value: PLAIN
        - name: CONSUMER_SASL_USERNAME
          valueFrom:
            secretKeyRef:
              key: KAFKA_SASL_USERNAME
              name: onms-passwords
        - name: CONSUMER_SASL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: KAFKA_SASL_PASSWORD
              name: onms-passwords
        - name: CONSUMER_AUTO_OFFSET_RESET
          value: latest
        - name: CONSUMER_MAX_PARTITION_FETCH_BYTES
          value: '5000000'
        # Kafka Producer
        - name: PRODUCER_SECURITY_PROTOCOL
          value: SASL_PLAINTEXT
        - name: PRODUCER_SASL_MECHANISM
          value: PLAIN
        - name: PRODUCER_SASL_USERNAME
          valueFrom:
            secretKeyRef:
              key: KAFKA_SASL_USERNAME
              name: onms-passwords
        - name: PRODUCER_SASL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: KAFKA_SASL_PASSWORD
              name: onms-passwords
        - name: PRODUCER_MESSAGE_MAX_BYTES
          value: '5000000'
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
        readinessProbe:
          exec:
            command: ['/bin/grpc_health_probe', '-addr', ':8990', '-rpc-timeout', '2s']
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 3
        livenessProbe:
          exec:
            command: ['/bin/grpc_health_probe', '-addr', ':8990', '-rpc-timeout', '2s']
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 3

