# @author Alejandro Galue <agalue@opennms.org>
#
# Warning: this excludes Cassandra to reduce the overhead on Minikube

---
bases:
- ../reduced

patchesStrategicMerge:
- patches/common-settings.yaml
- patches/external-access.yaml
- patches/opennms.core.yaml
