// Source: https://github.com/OpenNMS/opennms/blob/master/features/kafka/producer/src/main/proto/collectionset.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.4
// source: collectionset.proto

package producer

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type NumericAttribute_Type int32

const (
	NumericAttribute_GAUGE   NumericAttribute_Type = 0
	NumericAttribute_COUNTER NumericAttribute_Type = 1
)

// Enum value maps for NumericAttribute_Type.
var (
	NumericAttribute_Type_name = map[int32]string{
		0: "GAUGE",
		1: "COUNTER",
	}
	NumericAttribute_Type_value = map[string]int32{
		"GAUGE":   0,
		"COUNTER": 1,
	}
)

func (x NumericAttribute_Type) Enum() *NumericAttribute_Type {
	p := new(NumericAttribute_Type)
	*p = x
	return p
}

func (x NumericAttribute_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NumericAttribute_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_collectionset_proto_enumTypes[0].Descriptor()
}

func (NumericAttribute_Type) Type() protoreflect.EnumType {
	return &file_collectionset_proto_enumTypes[0]
}

func (x NumericAttribute_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NumericAttribute_Type.Descriptor instead.
func (NumericAttribute_Type) EnumDescriptor() ([]byte, []int) {
	return file_collectionset_proto_rawDescGZIP(), []int{1, 0}
}

type StringAttribute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *StringAttribute) Reset() {
	*x = StringAttribute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collectionset_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringAttribute) ProtoMessage() {}

func (x *StringAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_collectionset_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringAttribute.ProtoReflect.Descriptor instead.
func (*StringAttribute) Descriptor() ([]byte, []int) {
	return file_collectionset_proto_rawDescGZIP(), []int{0}
}

func (x *StringAttribute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StringAttribute) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type NumericAttribute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group string                `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Name  string                `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value float64               `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	Type  NumericAttribute_Type `protobuf:"varint,4,opt,name=type,proto3,enum=NumericAttribute_Type" json:"type,omitempty"`
}

func (x *NumericAttribute) Reset() {
	*x = NumericAttribute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collectionset_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NumericAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumericAttribute) ProtoMessage() {}

func (x *NumericAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_collectionset_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumericAttribute.ProtoReflect.Descriptor instead.
func (*NumericAttribute) Descriptor() ([]byte, []int) {
	return file_collectionset_proto_rawDescGZIP(), []int{1}
}

func (x *NumericAttribute) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *NumericAttribute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NumericAttribute) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *NumericAttribute) GetType() NumericAttribute_Type {
	if x != nil {
		return x.Type
	}
	return NumericAttribute_GAUGE
}

type NodeLevelResource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId        int64  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ForeignSource string `protobuf:"bytes,2,opt,name=foreign_source,json=foreignSource,proto3" json:"foreign_source,omitempty"`
	ForeignId     string `protobuf:"bytes,3,opt,name=foreign_id,json=foreignId,proto3" json:"foreign_id,omitempty"`
	NodeLabel     string `protobuf:"bytes,4,opt,name=node_label,json=nodeLabel,proto3" json:"node_label,omitempty"`
	Location      string `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *NodeLevelResource) Reset() {
	*x = NodeLevelResource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collectionset_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeLevelResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeLevelResource) ProtoMessage() {}

func (x *NodeLevelResource) ProtoReflect() protoreflect.Message {
	mi := &file_collectionset_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeLevelResource.ProtoReflect.Descriptor instead.
func (*NodeLevelResource) Descriptor() ([]byte, []int) {
	return file_collectionset_proto_rawDescGZIP(), []int{2}
}

func (x *NodeLevelResource) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *NodeLevelResource) GetForeignSource() string {
	if x != nil {
		return x.ForeignSource
	}
	return ""
}

func (x *NodeLevelResource) GetForeignId() string {
	if x != nil {
		return x.ForeignId
	}
	return ""
}

func (x *NodeLevelResource) GetNodeLabel() string {
	if x != nil {
		return x.NodeLabel
	}
	return ""
}

func (x *NodeLevelResource) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type InterfaceLevelResource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node     *NodeLevelResource `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Instance string             `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
}

func (x *InterfaceLevelResource) Reset() {
	*x = InterfaceLevelResource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collectionset_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InterfaceLevelResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceLevelResource) ProtoMessage() {}

func (x *InterfaceLevelResource) ProtoReflect() protoreflect.Message {
	mi := &file_collectionset_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceLevelResource.ProtoReflect.Descriptor instead.
func (*InterfaceLevelResource) Descriptor() ([]byte, []int) {
	return file_collectionset_proto_rawDescGZIP(), []int{3}
}

func (x *InterfaceLevelResource) GetNode() *NodeLevelResource {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *InterfaceLevelResource) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

type GenericTypeResource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node     *NodeLevelResource `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Type     string             `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Instance string             `protobuf:"bytes,3,opt,name=instance,proto3" json:"instance,omitempty"`
}

func (x *GenericTypeResource) Reset() {
	*x = GenericTypeResource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collectionset_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenericTypeResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericTypeResource) ProtoMessage() {}

func (x *GenericTypeResource) ProtoReflect() protoreflect.Message {
	mi := &file_collectionset_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericTypeResource.ProtoReflect.Descriptor instead.
func (*GenericTypeResource) Descriptor() ([]byte, []int) {
	return file_collectionset_proto_rawDescGZIP(), []int{4}
}

func (x *GenericTypeResource) GetNode() *NodeLevelResource {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *GenericTypeResource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GenericTypeResource) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

type ResponseTimeResource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Instance string `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Location string `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *ResponseTimeResource) Reset() {
	*x = ResponseTimeResource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collectionset_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseTimeResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseTimeResource) ProtoMessage() {}

func (x *ResponseTimeResource) ProtoReflect() protoreflect.Message {
	mi := &file_collectionset_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseTimeResource.ProtoReflect.Descriptor instead.
func (*ResponseTimeResource) Descriptor() ([]byte, []int) {
	return file_collectionset_proto_rawDescGZIP(), []int{5}
}

func (x *ResponseTimeResource) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *ResponseTimeResource) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type CollectionSetResource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Resource:
	//	*CollectionSetResource_Node
	//	*CollectionSetResource_Interface
	//	*CollectionSetResource_Generic
	//	*CollectionSetResource_Response
	Resource isCollectionSetResource_Resource `protobuf_oneof:"resource"`
	String_  []*StringAttribute               `protobuf:"bytes,10,rep,name=string,proto3" json:"string,omitempty"`
	Numeric  []*NumericAttribute              `protobuf:"bytes,11,rep,name=numeric,proto3" json:"numeric,omitempty"`
}

func (x *CollectionSetResource) Reset() {
	*x = CollectionSetResource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collectionset_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectionSetResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionSetResource) ProtoMessage() {}

func (x *CollectionSetResource) ProtoReflect() protoreflect.Message {
	mi := &file_collectionset_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionSetResource.ProtoReflect.Descriptor instead.
func (*CollectionSetResource) Descriptor() ([]byte, []int) {
	return file_collectionset_proto_rawDescGZIP(), []int{6}
}

func (m *CollectionSetResource) GetResource() isCollectionSetResource_Resource {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (x *CollectionSetResource) GetNode() *NodeLevelResource {
	if x, ok := x.GetResource().(*CollectionSetResource_Node); ok {
		return x.Node
	}
	return nil
}

func (x *CollectionSetResource) GetInterface() *InterfaceLevelResource {
	if x, ok := x.GetResource().(*CollectionSetResource_Interface); ok {
		return x.Interface
	}
	return nil
}

func (x *CollectionSetResource) GetGeneric() *GenericTypeResource {
	if x, ok := x.GetResource().(*CollectionSetResource_Generic); ok {
		return x.Generic
	}
	return nil
}

func (x *CollectionSetResource) GetResponse() *ResponseTimeResource {
	if x, ok := x.GetResource().(*CollectionSetResource_Response); ok {
		return x.Response
	}
	return nil
}

func (x *CollectionSetResource) GetString_() []*StringAttribute {
	if x != nil {
		return x.String_
	}
	return nil
}

func (x *CollectionSetResource) GetNumeric() []*NumericAttribute {
	if x != nil {
		return x.Numeric
	}
	return nil
}

type isCollectionSetResource_Resource interface {
	isCollectionSetResource_Resource()
}

type CollectionSetResource_Node struct {
	Node *NodeLevelResource `protobuf:"bytes,1,opt,name=node,proto3,oneof"`
}

type CollectionSetResource_Interface struct {
	Interface *InterfaceLevelResource `protobuf:"bytes,2,opt,name=interface,proto3,oneof"`
}

type CollectionSetResource_Generic struct {
	Generic *GenericTypeResource `protobuf:"bytes,3,opt,name=generic,proto3,oneof"`
}

type CollectionSetResource_Response struct {
	Response *ResponseTimeResource `protobuf:"bytes,4,opt,name=response,proto3,oneof"`
}

func (*CollectionSetResource_Node) isCollectionSetResource_Resource() {}

func (*CollectionSetResource_Interface) isCollectionSetResource_Resource() {}

func (*CollectionSetResource_Generic) isCollectionSetResource_Resource() {}

func (*CollectionSetResource_Response) isCollectionSetResource_Resource() {}

type CollectionSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp int64                    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Resource  []*CollectionSetResource `protobuf:"bytes,2,rep,name=resource,proto3" json:"resource,omitempty"`
}

func (x *CollectionSet) Reset() {
	*x = CollectionSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collectionset_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectionSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionSet) ProtoMessage() {}

func (x *CollectionSet) ProtoReflect() protoreflect.Message {
	mi := &file_collectionset_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionSet.ProtoReflect.Descriptor instead.
func (*CollectionSet) Descriptor() ([]byte, []int) {
	return file_collectionset_proto_rawDescGZIP(), []int{7}
}

func (x *CollectionSet) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CollectionSet) GetResource() []*CollectionSetResource {
	if x != nil {
		return x.Resource
	}
	return nil
}

var File_collectionset_proto protoreflect.FileDescriptor

var file_collectionset_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x65, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3b, 0x0a, 0x0f, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x41,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x9e, 0x01, 0x0a, 0x10, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x41, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x41,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x22, 0x1e, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x47,
	0x41, 0x55, 0x47, 0x45, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x45,
	0x52, 0x10, 0x01, 0x22, 0xad, 0x01, 0x0a, 0x11, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x64,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65,
	0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x66, 0x6f, 0x72, 0x65, 0x69, 0x67, 0x6e, 0x5f, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x66, 0x6f, 0x72, 0x65,
	0x69, 0x67, 0x6e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x6f, 0x72,
	0x65, 0x69, 0x67, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66,
	0x6f, 0x72, 0x65, 0x69, 0x67, 0x6e, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x6f, 0x64, 0x65,
	0x5f, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x6f,
	0x64, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x5c, 0x0a, 0x16, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x26, 0x0a,
	0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x4e, 0x6f,
	0x64, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52,
	0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x22, 0x6d, 0x0a, 0x13, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x22, 0x4e, 0x0a, 0x14, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0xc4, 0x02, 0x0a, 0x15, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x6e, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x48, 0x00, 0x52, 0x04,
	0x6e, 0x6f, 0x64, 0x65, 0x12, 0x37, 0x0a, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x48, 0x00, 0x52, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x30, 0x0a,
	0x07, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x48, 0x00, 0x52, 0x07, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x12,
	0x33, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x0a,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x41, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x52, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x2b,
	0x0a, 0x07, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x52, 0x07, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x42, 0x0a, 0x0a, 0x08, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x61, 0x0a, 0x0d, 0x43, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x32, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_collectionset_proto_rawDescOnce sync.Once
	file_collectionset_proto_rawDescData = file_collectionset_proto_rawDesc
)

func file_collectionset_proto_rawDescGZIP() []byte {
	file_collectionset_proto_rawDescOnce.Do(func() {
		file_collectionset_proto_rawDescData = protoimpl.X.CompressGZIP(file_collectionset_proto_rawDescData)
	})
	return file_collectionset_proto_rawDescData
}

var file_collectionset_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_collectionset_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_collectionset_proto_goTypes = []interface{}{
	(NumericAttribute_Type)(0),     // 0: NumericAttribute.Type
	(*StringAttribute)(nil),        // 1: StringAttribute
	(*NumericAttribute)(nil),       // 2: NumericAttribute
	(*NodeLevelResource)(nil),      // 3: NodeLevelResource
	(*InterfaceLevelResource)(nil), // 4: InterfaceLevelResource
	(*GenericTypeResource)(nil),    // 5: GenericTypeResource
	(*ResponseTimeResource)(nil),   // 6: ResponseTimeResource
	(*CollectionSetResource)(nil),  // 7: CollectionSetResource
	(*CollectionSet)(nil),          // 8: CollectionSet
}
var file_collectionset_proto_depIdxs = []int32{
	0,  // 0: NumericAttribute.type:type_name -> NumericAttribute.Type
	3,  // 1: InterfaceLevelResource.node:type_name -> NodeLevelResource
	3,  // 2: GenericTypeResource.node:type_name -> NodeLevelResource
	3,  // 3: CollectionSetResource.node:type_name -> NodeLevelResource
	4,  // 4: CollectionSetResource.interface:type_name -> InterfaceLevelResource
	5,  // 5: CollectionSetResource.generic:type_name -> GenericTypeResource
	6,  // 6: CollectionSetResource.response:type_name -> ResponseTimeResource
	1,  // 7: CollectionSetResource.string:type_name -> StringAttribute
	2,  // 8: CollectionSetResource.numeric:type_name -> NumericAttribute
	7,  // 9: CollectionSet.resource:type_name -> CollectionSetResource
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_collectionset_proto_init() }
func file_collectionset_proto_init() {
	if File_collectionset_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_collectionset_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringAttribute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collectionset_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NumericAttribute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collectionset_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeLevelResource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collectionset_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InterfaceLevelResource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collectionset_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenericTypeResource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collectionset_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseTimeResource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collectionset_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectionSetResource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collectionset_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectionSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_collectionset_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*CollectionSetResource_Node)(nil),
		(*CollectionSetResource_Interface)(nil),
		(*CollectionSetResource_Generic)(nil),
		(*CollectionSetResource_Response)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_collectionset_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_collectionset_proto_goTypes,
		DependencyIndexes: file_collectionset_proto_depIdxs,
		EnumInfos:         file_collectionset_proto_enumTypes,
		MessageInfos:      file_collectionset_proto_msgTypes,
	}.Build()
	File_collectionset_proto = out.File
	file_collectionset_proto_rawDesc = nil
	file_collectionset_proto_goTypes = nil
	file_collectionset_proto_depIdxs = nil
}
