// Code generated by protoc-gen-go. DO NOT EDIT.
// source: opennms-kafka-producer.proto

package producer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The values differ from the standard codes in OpenNMS
// since proto3 enforces us to start at 0
type Severity int32

const (
	Severity_INDETERMINATE Severity = 0
	Severity_CLEARED       Severity = 1
	Severity_NORMAL        Severity = 2
	Severity_WARNING       Severity = 3
	Severity_MINOR         Severity = 4
	Severity_MAJOR         Severity = 5
	Severity_CRITICAL      Severity = 6
)

var Severity_name = map[int32]string{
	0: "INDETERMINATE",
	1: "CLEARED",
	2: "NORMAL",
	3: "WARNING",
	4: "MINOR",
	5: "MAJOR",
	6: "CRITICAL",
}

var Severity_value = map[string]int32{
	"INDETERMINATE": 0,
	"CLEARED":       1,
	"NORMAL":        2,
	"WARNING":       3,
	"MINOR":         4,
	"MAJOR":         5,
	"CRITICAL":      6,
}

func (x Severity) String() string {
	return proto.EnumName(Severity_name, int32(x))
}

func (Severity) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e5238ae8b6d75269, []int{0}
}

type Alarm_Type int32

const (
	Alarm_PROBLEM_WITH_CLEAR    Alarm_Type = 0
	Alarm_CLEAR                 Alarm_Type = 1
	Alarm_PROBLEM_WITHOUT_CLEAR Alarm_Type = 2
)

var Alarm_Type_name = map[int32]string{
	0: "PROBLEM_WITH_CLEAR",
	1: "CLEAR",
	2: "PROBLEM_WITHOUT_CLEAR",
}

var Alarm_Type_value = map[string]int32{
	"PROBLEM_WITH_CLEAR":    0,
	"CLEAR":                 1,
	"PROBLEM_WITHOUT_CLEAR": 2,
}

func (x Alarm_Type) String() string {
	return proto.EnumName(Alarm_Type_name, int32(x))
}

func (Alarm_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e5238ae8b6d75269, []int{3, 0}
}

type AlarmFeedback_FeedbackType int32

const (
	AlarmFeedback_FALSE_POSITIVE AlarmFeedback_FeedbackType = 0
	AlarmFeedback_FALSE_NEGATIVE AlarmFeedback_FeedbackType = 1
	AlarmFeedback_CORRECT        AlarmFeedback_FeedbackType = 2
	AlarmFeedback_UNKNOWN        AlarmFeedback_FeedbackType = 3
)

var AlarmFeedback_FeedbackType_name = map[int32]string{
	0: "FALSE_POSITIVE",
	1: "FALSE_NEGATIVE",
	2: "CORRECT",
	3: "UNKNOWN",
}

var AlarmFeedback_FeedbackType_value = map[string]int32{
	"FALSE_POSITIVE": 0,
	"FALSE_NEGATIVE": 1,
	"CORRECT":        2,
	"UNKNOWN":        3,
}

func (x AlarmFeedback_FeedbackType) String() string {
	return proto.EnumName(AlarmFeedback_FeedbackType_name, int32(x))
}

func (AlarmFeedback_FeedbackType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e5238ae8b6d75269, []int{4, 0}
}

type IpInterface_PrimaryType int32

const (
	IpInterface_PRIMARY      IpInterface_PrimaryType = 0
	IpInterface_SECONDARY    IpInterface_PrimaryType = 1
	IpInterface_NOT_ELIGIBLE IpInterface_PrimaryType = 2
)

var IpInterface_PrimaryType_name = map[int32]string{
	0: "PRIMARY",
	1: "SECONDARY",
	2: "NOT_ELIGIBLE",
}

var IpInterface_PrimaryType_value = map[string]int32{
	"PRIMARY":      0,
	"SECONDARY":    1,
	"NOT_ELIGIBLE": 2,
}

func (x IpInterface_PrimaryType) String() string {
	return proto.EnumName(IpInterface_PrimaryType_name, int32(x))
}

func (IpInterface_PrimaryType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e5238ae8b6d75269, []int{5, 0}
}

type TopologyRef_Protocol int32

const (
	TopologyRef_LLDP        TopologyRef_Protocol = 0
	TopologyRef_OSPF        TopologyRef_Protocol = 1
	TopologyRef_ISIS        TopologyRef_Protocol = 2
	TopologyRef_BRIDGE      TopologyRef_Protocol = 3
	TopologyRef_CDP         TopologyRef_Protocol = 4
	TopologyRef_USERDEFINED TopologyRef_Protocol = 5
)

var TopologyRef_Protocol_name = map[int32]string{
	0: "LLDP",
	1: "OSPF",
	2: "ISIS",
	3: "BRIDGE",
	4: "CDP",
	5: "USERDEFINED",
}

var TopologyRef_Protocol_value = map[string]int32{
	"LLDP":        0,
	"OSPF":        1,
	"ISIS":        2,
	"BRIDGE":      3,
	"CDP":         4,
	"USERDEFINED": 5,
}

func (x TopologyRef_Protocol) String() string {
	return proto.EnumName(TopologyRef_Protocol_name, int32(x))
}

func (TopologyRef_Protocol) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e5238ae8b6d75269, []int{10, 0}
}

type NodeCriteria struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ForeignSource        string   `protobuf:"bytes,2,opt,name=foreign_source,json=foreignSource,proto3" json:"foreign_source,omitempty"`
	ForeignId            string   `protobuf:"bytes,3,opt,name=foreign_id,json=foreignId,proto3" json:"foreign_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeCriteria) Reset()         { *m = NodeCriteria{} }
func (m *NodeCriteria) String() string { return proto.CompactTextString(m) }
func (*NodeCriteria) ProtoMessage()    {}
func (*NodeCriteria) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5238ae8b6d75269, []int{0}
}

func (m *NodeCriteria) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeCriteria.Unmarshal(m, b)
}
func (m *NodeCriteria) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeCriteria.Marshal(b, m, deterministic)
}
func (m *NodeCriteria) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeCriteria.Merge(m, src)
}
func (m *NodeCriteria) XXX_Size() int {
	return xxx_messageInfo_NodeCriteria.Size(m)
}
func (m *NodeCriteria) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeCriteria.DiscardUnknown(m)
}

var xxx_messageInfo_NodeCriteria proto.InternalMessageInfo

func (m *NodeCriteria) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NodeCriteria) GetForeignSource() string {
	if m != nil {
		return m.ForeignSource
	}
	return ""
}

func (m *NodeCriteria) GetForeignId() string {
	if m != nil {
		return m.ForeignId
	}
	return ""
}

type EventParameter struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventParameter) Reset()         { *m = EventParameter{} }
func (m *EventParameter) String() string { return proto.CompactTextString(m) }
func (*EventParameter) ProtoMessage()    {}
func (*EventParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5238ae8b6d75269, []int{1}
}

func (m *EventParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventParameter.Unmarshal(m, b)
}
func (m *EventParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventParameter.Marshal(b, m, deterministic)
}
func (m *EventParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventParameter.Merge(m, src)
}
func (m *EventParameter) XXX_Size() int {
	return xxx_messageInfo_EventParameter.Size(m)
}
func (m *EventParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_EventParameter.DiscardUnknown(m)
}

var xxx_messageInfo_EventParameter proto.InternalMessageInfo

func (m *EventParameter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EventParameter) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *EventParameter) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Event struct {
	Id                   uint64            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uei                  string            `protobuf:"bytes,2,opt,name=uei,proto3" json:"uei,omitempty"`
	Label                string            `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Time                 uint64            `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
	Source               string            `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	Parameter            []*EventParameter `protobuf:"bytes,6,rep,name=parameter,proto3" json:"parameter,omitempty"`
	CreateTime           uint64            `protobuf:"varint,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Description          string            `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	LogMessage           string            `protobuf:"bytes,9,opt,name=log_message,json=logMessage,proto3" json:"log_message,omitempty"`
	Severity             Severity          `protobuf:"varint,10,opt,name=severity,proto3,enum=Severity" json:"severity,omitempty"`
	Log                  bool              `protobuf:"varint,11,opt,name=log,proto3" json:"log,omitempty"`
	Display              bool              `protobuf:"varint,12,opt,name=display,proto3" json:"display,omitempty"`
	NodeCriteria         *NodeCriteria     `protobuf:"bytes,13,opt,name=node_criteria,json=nodeCriteria,proto3" json:"node_criteria,omitempty"`
	IpAddress            string            `protobuf:"bytes,14,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5238ae8b6d75269, []int{2}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Event) GetUei() string {
	if m != nil {
		return m.Uei
	}
	return ""
}

func (m *Event) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Event) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Event) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Event) GetParameter() []*EventParameter {
	if m != nil {
		return m.Parameter
	}
	return nil
}

func (m *Event) GetCreateTime() uint64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Event) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Event) GetLogMessage() string {
	if m != nil {
		return m.LogMessage
	}
	return ""
}

func (m *Event) GetSeverity() Severity {
	if m != nil {
		return m.Severity
	}
	return Severity_INDETERMINATE
}

func (m *Event) GetLog() bool {
	if m != nil {
		return m.Log
	}
	return false
}

func (m *Event) GetDisplay() bool {
	if m != nil {
		return m.Display
	}
	return false
}

func (m *Event) GetNodeCriteria() *NodeCriteria {
	if m != nil {
		return m.NodeCriteria
	}
	return nil
}

func (m *Event) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

type Alarm struct {
	Id                    uint64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uei                   string        `protobuf:"bytes,2,opt,name=uei,proto3" json:"uei,omitempty"`
	NodeCriteria          *NodeCriteria `protobuf:"bytes,3,opt,name=node_criteria,json=nodeCriteria,proto3" json:"node_criteria,omitempty"`
	IpAddress             string        `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	ServiceName           string        `protobuf:"bytes,5,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ReductionKey          string        `protobuf:"bytes,6,opt,name=reduction_key,json=reductionKey,proto3" json:"reduction_key,omitempty"`
	Type                  Alarm_Type    `protobuf:"varint,7,opt,name=type,proto3,enum=Alarm_Type" json:"type,omitempty"`
	Count                 uint64        `protobuf:"varint,8,opt,name=count,proto3" json:"count,omitempty"`
	Severity              Severity      `protobuf:"varint,9,opt,name=severity,proto3,enum=Severity" json:"severity,omitempty"`
	FirstEventTime        uint64        `protobuf:"varint,10,opt,name=first_event_time,json=firstEventTime,proto3" json:"first_event_time,omitempty"`
	Description           string        `protobuf:"bytes,11,opt,name=description,proto3" json:"description,omitempty"`
	LogMessage            string        `protobuf:"bytes,12,opt,name=log_message,json=logMessage,proto3" json:"log_message,omitempty"`
	AckUser               string        `protobuf:"bytes,13,opt,name=ack_user,json=ackUser,proto3" json:"ack_user,omitempty"`
	AckTime               uint64        `protobuf:"varint,14,opt,name=ack_time,json=ackTime,proto3" json:"ack_time,omitempty"`
	LastEvent             *Event        `protobuf:"bytes,15,opt,name=last_event,json=lastEvent,proto3" json:"last_event,omitempty"`
	LastEventTime         uint64        `protobuf:"varint,16,opt,name=last_event_time,json=lastEventTime,proto3" json:"last_event_time,omitempty"`
	IfIndex               uint32        `protobuf:"varint,17,opt,name=if_index,json=ifIndex,proto3" json:"if_index,omitempty"`
	OperatorInstructions  string        `protobuf:"bytes,18,opt,name=operator_instructions,json=operatorInstructions,proto3" json:"operator_instructions,omitempty"`
	ClearKey              string        `protobuf:"bytes,19,opt,name=clear_key,json=clearKey,proto3" json:"clear_key,omitempty"`
	ManagedObjectInstance string        `protobuf:"bytes,20,opt,name=managed_object_instance,json=managedObjectInstance,proto3" json:"managed_object_instance,omitempty"`
	ManagedObjectType     string        `protobuf:"bytes,21,opt,name=managed_object_type,json=managedObjectType,proto3" json:"managed_object_type,omitempty"`
	RelatedAlarm          []*Alarm      `protobuf:"bytes,22,rep,name=relatedAlarm,proto3" json:"relatedAlarm,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}      `json:"-"`
	XXX_unrecognized      []byte        `json:"-"`
	XXX_sizecache         int32         `json:"-"`
}

func (m *Alarm) Reset()         { *m = Alarm{} }
func (m *Alarm) String() string { return proto.CompactTextString(m) }
func (*Alarm) ProtoMessage()    {}
func (*Alarm) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5238ae8b6d75269, []int{3}
}

func (m *Alarm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Alarm.Unmarshal(m, b)
}
func (m *Alarm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Alarm.Marshal(b, m, deterministic)
}
func (m *Alarm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Alarm.Merge(m, src)
}
func (m *Alarm) XXX_Size() int {
	return xxx_messageInfo_Alarm.Size(m)
}
func (m *Alarm) XXX_DiscardUnknown() {
	xxx_messageInfo_Alarm.DiscardUnknown(m)
}

var xxx_messageInfo_Alarm proto.InternalMessageInfo

func (m *Alarm) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Alarm) GetUei() string {
	if m != nil {
		return m.Uei
	}
	return ""
}

func (m *Alarm) GetNodeCriteria() *NodeCriteria {
	if m != nil {
		return m.NodeCriteria
	}
	return nil
}

func (m *Alarm) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

func (m *Alarm) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *Alarm) GetReductionKey() string {
	if m != nil {
		return m.ReductionKey
	}
	return ""
}

func (m *Alarm) GetType() Alarm_Type {
	if m != nil {
		return m.Type
	}
	return Alarm_PROBLEM_WITH_CLEAR
}

func (m *Alarm) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Alarm) GetSeverity() Severity {
	if m != nil {
		return m.Severity
	}
	return Severity_INDETERMINATE
}

func (m *Alarm) GetFirstEventTime() uint64 {
	if m != nil {
		return m.FirstEventTime
	}
	return 0
}

func (m *Alarm) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Alarm) GetLogMessage() string {
	if m != nil {
		return m.LogMessage
	}
	return ""
}

func (m *Alarm) GetAckUser() string {
	if m != nil {
		return m.AckUser
	}
	return ""
}

func (m *Alarm) GetAckTime() uint64 {
	if m != nil {
		return m.AckTime
	}
	return 0
}

func (m *Alarm) GetLastEvent() *Event {
	if m != nil {
		return m.LastEvent
	}
	return nil
}

func (m *Alarm) GetLastEventTime() uint64 {
	if m != nil {
		return m.LastEventTime
	}
	return 0
}

func (m *Alarm) GetIfIndex() uint32 {
	if m != nil {
		return m.IfIndex
	}
	return 0
}

func (m *Alarm) GetOperatorInstructions() string {
	if m != nil {
		return m.OperatorInstructions
	}
	return ""
}

func (m *Alarm) GetClearKey() string {
	if m != nil {
		return m.ClearKey
	}
	return ""
}

func (m *Alarm) GetManagedObjectInstance() string {
	if m != nil {
		return m.ManagedObjectInstance
	}
	return ""
}

func (m *Alarm) GetManagedObjectType() string {
	if m != nil {
		return m.ManagedObjectType
	}
	return ""
}

func (m *Alarm) GetRelatedAlarm() []*Alarm {
	if m != nil {
		return m.RelatedAlarm
	}
	return nil
}

type AlarmFeedback struct {
	SituationKey         string                     `protobuf:"bytes,1,opt,name=situation_key,json=situationKey,proto3" json:"situation_key,omitempty"`
	SituationFingerprint string                     `protobuf:"bytes,2,opt,name=situation_fingerprint,json=situationFingerprint,proto3" json:"situation_fingerprint,omitempty"`
	AlarmKey             string                     `protobuf:"bytes,3,opt,name=alarm_key,json=alarmKey,proto3" json:"alarm_key,omitempty"`
	FeedbackType         AlarmFeedback_FeedbackType `protobuf:"varint,4,opt,name=feedback_type,json=feedbackType,proto3,enum=AlarmFeedback_FeedbackType" json:"feedback_type,omitempty"`
	Reason               string                     `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	User                 string                     `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	Timestamp            uint64                     `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *AlarmFeedback) Reset()         { *m = AlarmFeedback{} }
func (m *AlarmFeedback) String() string { return proto.CompactTextString(m) }
func (*AlarmFeedback) ProtoMessage()    {}
func (*AlarmFeedback) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5238ae8b6d75269, []int{4}
}

func (m *AlarmFeedback) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlarmFeedback.Unmarshal(m, b)
}
func (m *AlarmFeedback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlarmFeedback.Marshal(b, m, deterministic)
}
func (m *AlarmFeedback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlarmFeedback.Merge(m, src)
}
func (m *AlarmFeedback) XXX_Size() int {
	return xxx_messageInfo_AlarmFeedback.Size(m)
}
func (m *AlarmFeedback) XXX_DiscardUnknown() {
	xxx_messageInfo_AlarmFeedback.DiscardUnknown(m)
}

var xxx_messageInfo_AlarmFeedback proto.InternalMessageInfo

func (m *AlarmFeedback) GetSituationKey() string {
	if m != nil {
		return m.SituationKey
	}
	return ""
}

func (m *AlarmFeedback) GetSituationFingerprint() string {
	if m != nil {
		return m.SituationFingerprint
	}
	return ""
}

func (m *AlarmFeedback) GetAlarmKey() string {
	if m != nil {
		return m.AlarmKey
	}
	return ""
}

func (m *AlarmFeedback) GetFeedbackType() AlarmFeedback_FeedbackType {
	if m != nil {
		return m.FeedbackType
	}
	return AlarmFeedback_FALSE_POSITIVE
}

func (m *AlarmFeedback) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *AlarmFeedback) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *AlarmFeedback) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type IpInterface struct {
	Id                   uint64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IpAddress            string                  `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	IfIndex              uint32                  `protobuf:"varint,3,opt,name=if_index,json=ifIndex,proto3" json:"if_index,omitempty"`
	PrimaryType          IpInterface_PrimaryType `protobuf:"varint,4,opt,name=primary_type,json=primaryType,proto3,enum=IpInterface_PrimaryType" json:"primary_type,omitempty"`
	Service              []string                `protobuf:"bytes,5,rep,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *IpInterface) Reset()         { *m = IpInterface{} }
func (m *IpInterface) String() string { return proto.CompactTextString(m) }
func (*IpInterface) ProtoMessage()    {}
func (*IpInterface) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5238ae8b6d75269, []int{5}
}

func (m *IpInterface) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IpInterface.Unmarshal(m, b)
}
func (m *IpInterface) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IpInterface.Marshal(b, m, deterministic)
}
func (m *IpInterface) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IpInterface.Merge(m, src)
}
func (m *IpInterface) XXX_Size() int {
	return xxx_messageInfo_IpInterface.Size(m)
}
func (m *IpInterface) XXX_DiscardUnknown() {
	xxx_messageInfo_IpInterface.DiscardUnknown(m)
}

var xxx_messageInfo_IpInterface proto.InternalMessageInfo

func (m *IpInterface) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *IpInterface) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

func (m *IpInterface) GetIfIndex() uint32 {
	if m != nil {
		return m.IfIndex
	}
	return 0
}

func (m *IpInterface) GetPrimaryType() IpInterface_PrimaryType {
	if m != nil {
		return m.PrimaryType
	}
	return IpInterface_PRIMARY
}

func (m *IpInterface) GetService() []string {
	if m != nil {
		return m.Service
	}
	return nil
}

type SnmpInterface struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IfIndex              uint32   `protobuf:"varint,2,opt,name=if_index,json=ifIndex,proto3" json:"if_index,omitempty"`
	IfDescr              string   `protobuf:"bytes,3,opt,name=if_descr,json=ifDescr,proto3" json:"if_descr,omitempty"`
	IfType               uint32   `protobuf:"varint,4,opt,name=if_type,json=ifType,proto3" json:"if_type,omitempty"`
	IfName               string   `protobuf:"bytes,5,opt,name=if_name,json=ifName,proto3" json:"if_name,omitempty"`
	IfSpeed              uint64   `protobuf:"varint,6,opt,name=if_speed,json=ifSpeed,proto3" json:"if_speed,omitempty"`
	IfPhysAddress        string   `protobuf:"bytes,7,opt,name=if_phys_address,json=ifPhysAddress,proto3" json:"if_phys_address,omitempty"`
	IfAdminStatus        uint32   `protobuf:"varint,8,opt,name=if_admin_status,json=ifAdminStatus,proto3" json:"if_admin_status,omitempty"`
	IfOperStatus         uint32   `protobuf:"varint,9,opt,name=if_oper_status,json=ifOperStatus,proto3" json:"if_oper_status,omitempty"`
	IfAlias              string   `protobuf:"bytes,10,opt,name=if_alias,json=ifAlias,proto3" json:"if_alias,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SnmpInterface) Reset()         { *m = SnmpInterface{} }
func (m *SnmpInterface) String() string { return proto.CompactTextString(m) }
func (*SnmpInterface) ProtoMessage()    {}
func (*SnmpInterface) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5238ae8b6d75269, []int{6}
}

func (m *SnmpInterface) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SnmpInterface.Unmarshal(m, b)
}
func (m *SnmpInterface) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SnmpInterface.Marshal(b, m, deterministic)
}
func (m *SnmpInterface) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnmpInterface.Merge(m, src)
}
func (m *SnmpInterface) XXX_Size() int {
	return xxx_messageInfo_SnmpInterface.Size(m)
}
func (m *SnmpInterface) XXX_DiscardUnknown() {
	xxx_messageInfo_SnmpInterface.DiscardUnknown(m)
}

var xxx_messageInfo_SnmpInterface proto.InternalMessageInfo

func (m *SnmpInterface) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SnmpInterface) GetIfIndex() uint32 {
	if m != nil {
		return m.IfIndex
	}
	return 0
}

func (m *SnmpInterface) GetIfDescr() string {
	if m != nil {
		return m.IfDescr
	}
	return ""
}

func (m *SnmpInterface) GetIfType() uint32 {
	if m != nil {
		return m.IfType
	}
	return 0
}

func (m *SnmpInterface) GetIfName() string {
	if m != nil {
		return m.IfName
	}
	return ""
}

func (m *SnmpInterface) GetIfSpeed() uint64 {
	if m != nil {
		return m.IfSpeed
	}
	return 0
}

func (m *SnmpInterface) GetIfPhysAddress() string {
	if m != nil {
		return m.IfPhysAddress
	}
	return ""
}

func (m *SnmpInterface) GetIfAdminStatus() uint32 {
	if m != nil {
		return m.IfAdminStatus
	}
	return 0
}

func (m *SnmpInterface) GetIfOperStatus() uint32 {
	if m != nil {
		return m.IfOperStatus
	}
	return 0
}

func (m *SnmpInterface) GetIfAlias() string {
	if m != nil {
		return m.IfAlias
	}
	return ""
}

type HwAlias struct {
	Index                uint32   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Oid                  string   `protobuf:"bytes,2,opt,name=oid,proto3" json:"oid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HwAlias) Reset()         { *m = HwAlias{} }
func (m *HwAlias) String() string { return proto.CompactTextString(m) }
func (*HwAlias) ProtoMessage()    {}
func (*HwAlias) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5238ae8b6d75269, []int{7}
}

func (m *HwAlias) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HwAlias.Unmarshal(m, b)
}
func (m *HwAlias) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HwAlias.Marshal(b, m, deterministic)
}
func (m *HwAlias) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HwAlias.Merge(m, src)
}
func (m *HwAlias) XXX_Size() int {
	return xxx_messageInfo_HwAlias.Size(m)
}
func (m *HwAlias) XXX_DiscardUnknown() {
	xxx_messageInfo_HwAlias.DiscardUnknown(m)
}

var xxx_messageInfo_HwAlias proto.InternalMessageInfo

func (m *HwAlias) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *HwAlias) GetOid() string {
	if m != nil {
		return m.Oid
	}
	return ""
}

type HwEntity struct {
	EntPhysicalIndex      uint32      `protobuf:"varint,1,opt,name=ent_physical_index,json=entPhysicalIndex,proto3" json:"ent_physical_index,omitempty"`
	EntityId              uint32      `protobuf:"varint,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	EntPhysicalClass      string      `protobuf:"bytes,3,opt,name=ent_physical_class,json=entPhysicalClass,proto3" json:"ent_physical_class,omitempty"`
	EntPhysicalDescr      string      `protobuf:"bytes,4,opt,name=ent_physical_descr,json=entPhysicalDescr,proto3" json:"ent_physical_descr,omitempty"`
	EntPhysicalIsFru      bool        `protobuf:"varint,5,opt,name=ent_physical_is_fru,json=entPhysicalIsFru,proto3" json:"ent_physical_is_fru,omitempty"`
	EntPhysicalName       string      `protobuf:"bytes,6,opt,name=ent_physical_name,json=entPhysicalName,proto3" json:"ent_physical_name,omitempty"`
	EntPhysicalVendorType string      `protobuf:"bytes,7,opt,name=ent_physical_vendor_type,json=entPhysicalVendorType,proto3" json:"ent_physical_vendor_type,omitempty"`
	EntHwAlias            []*HwAlias  `protobuf:"bytes,8,rep,name=ent_hw_alias,json=entHwAlias,proto3" json:"ent_hw_alias,omitempty"`
	Children              []*HwEntity `protobuf:"bytes,9,rep,name=children,proto3" json:"children,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}    `json:"-"`
	XXX_unrecognized      []byte      `json:"-"`
	XXX_sizecache         int32       `json:"-"`
}

func (m *HwEntity) Reset()         { *m = HwEntity{} }
func (m *HwEntity) String() string { return proto.CompactTextString(m) }
func (*HwEntity) ProtoMessage()    {}
func (*HwEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5238ae8b6d75269, []int{8}
}

func (m *HwEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HwEntity.Unmarshal(m, b)
}
func (m *HwEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HwEntity.Marshal(b, m, deterministic)
}
func (m *HwEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HwEntity.Merge(m, src)
}
func (m *HwEntity) XXX_Size() int {
	return xxx_messageInfo_HwEntity.Size(m)
}
func (m *HwEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_HwEntity.DiscardUnknown(m)
}

var xxx_messageInfo_HwEntity proto.InternalMessageInfo

func (m *HwEntity) GetEntPhysicalIndex() uint32 {
	if m != nil {
		return m.EntPhysicalIndex
	}
	return 0
}

func (m *HwEntity) GetEntityId() uint32 {
	if m != nil {
		return m.EntityId
	}
	return 0
}

func (m *HwEntity) GetEntPhysicalClass() string {
	if m != nil {
		return m.EntPhysicalClass
	}
	return ""
}

func (m *HwEntity) GetEntPhysicalDescr() string {
	if m != nil {
		return m.EntPhysicalDescr
	}
	return ""
}

func (m *HwEntity) GetEntPhysicalIsFru() bool {
	if m != nil {
		return m.EntPhysicalIsFru
	}
	return false
}

func (m *HwEntity) GetEntPhysicalName() string {
	if m != nil {
		return m.EntPhysicalName
	}
	return ""
}

func (m *HwEntity) GetEntPhysicalVendorType() string {
	if m != nil {
		return m.EntPhysicalVendorType
	}
	return ""
}

func (m *HwEntity) GetEntHwAlias() []*HwAlias {
	if m != nil {
		return m.EntHwAlias
	}
	return nil
}

func (m *HwEntity) GetChildren() []*HwEntity {
	if m != nil {
		return m.Children
	}
	return nil
}

type Node struct {
	Id                   uint64           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ForeignSource        string           `protobuf:"bytes,2,opt,name=foreign_source,json=foreignSource,proto3" json:"foreign_source,omitempty"`
	ForeignId            string           `protobuf:"bytes,3,opt,name=foreign_id,json=foreignId,proto3" json:"foreign_id,omitempty"`
	Location             string           `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Category             []string         `protobuf:"bytes,5,rep,name=category,proto3" json:"category,omitempty"`
	Label                string           `protobuf:"bytes,6,opt,name=label,proto3" json:"label,omitempty"`
	CreateTime           uint64           `protobuf:"varint,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	SysContact           string           `protobuf:"bytes,8,opt,name=sys_contact,json=sysContact,proto3" json:"sys_contact,omitempty"`
	SysDescription       string           `protobuf:"bytes,9,opt,name=sys_description,json=sysDescription,proto3" json:"sys_description,omitempty"`
	SysObjectId          string           `protobuf:"bytes,10,opt,name=sys_object_id,json=sysObjectId,proto3" json:"sys_object_id,omitempty"`
	IpInterface          []*IpInterface   `protobuf:"bytes,11,rep,name=ip_interface,json=ipInterface,proto3" json:"ip_interface,omitempty"`
	SnmpInterface        []*SnmpInterface `protobuf:"bytes,12,rep,name=snmp_interface,json=snmpInterface,proto3" json:"snmp_interface,omitempty"`
	HwInventory          *HwEntity        `protobuf:"bytes,13,opt,name=hw_inventory,json=hwInventory,proto3" json:"hw_inventory,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5238ae8b6d75269, []int{9}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Node) GetForeignSource() string {
	if m != nil {
		return m.ForeignSource
	}
	return ""
}

func (m *Node) GetForeignId() string {
	if m != nil {
		return m.ForeignId
	}
	return ""
}

func (m *Node) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Node) GetCategory() []string {
	if m != nil {
		return m.Category
	}
	return nil
}

func (m *Node) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Node) GetCreateTime() uint64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Node) GetSysContact() string {
	if m != nil {
		return m.SysContact
	}
	return ""
}

func (m *Node) GetSysDescription() string {
	if m != nil {
		return m.SysDescription
	}
	return ""
}

func (m *Node) GetSysObjectId() string {
	if m != nil {
		return m.SysObjectId
	}
	return ""
}

func (m *Node) GetIpInterface() []*IpInterface {
	if m != nil {
		return m.IpInterface
	}
	return nil
}

func (m *Node) GetSnmpInterface() []*SnmpInterface {
	if m != nil {
		return m.SnmpInterface
	}
	return nil
}

func (m *Node) GetHwInventory() *HwEntity {
	if m != nil {
		return m.HwInventory
	}
	return nil
}

type TopologyRef struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Protocol             TopologyRef_Protocol `protobuf:"varint,2,opt,name=protocol,proto3,enum=TopologyRef_Protocol" json:"protocol,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TopologyRef) Reset()         { *m = TopologyRef{} }
func (m *TopologyRef) String() string { return proto.CompactTextString(m) }
func (*TopologyRef) ProtoMessage()    {}
func (*TopologyRef) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5238ae8b6d75269, []int{10}
}

func (m *TopologyRef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopologyRef.Unmarshal(m, b)
}
func (m *TopologyRef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopologyRef.Marshal(b, m, deterministic)
}
func (m *TopologyRef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopologyRef.Merge(m, src)
}
func (m *TopologyRef) XXX_Size() int {
	return xxx_messageInfo_TopologyRef.Size(m)
}
func (m *TopologyRef) XXX_DiscardUnknown() {
	xxx_messageInfo_TopologyRef.DiscardUnknown(m)
}

var xxx_messageInfo_TopologyRef proto.InternalMessageInfo

func (m *TopologyRef) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TopologyRef) GetProtocol() TopologyRef_Protocol {
	if m != nil {
		return m.Protocol
	}
	return TopologyRef_LLDP
}

type TopologySegment struct {
	Ref                  *TopologyRef `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TopologySegment) Reset()         { *m = TopologySegment{} }
func (m *TopologySegment) String() string { return proto.CompactTextString(m) }
func (*TopologySegment) ProtoMessage()    {}
func (*TopologySegment) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5238ae8b6d75269, []int{11}
}

func (m *TopologySegment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopologySegment.Unmarshal(m, b)
}
func (m *TopologySegment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopologySegment.Marshal(b, m, deterministic)
}
func (m *TopologySegment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopologySegment.Merge(m, src)
}
func (m *TopologySegment) XXX_Size() int {
	return xxx_messageInfo_TopologySegment.Size(m)
}
func (m *TopologySegment) XXX_DiscardUnknown() {
	xxx_messageInfo_TopologySegment.DiscardUnknown(m)
}

var xxx_messageInfo_TopologySegment proto.InternalMessageInfo

func (m *TopologySegment) GetRef() *TopologyRef {
	if m != nil {
		return m.Ref
	}
	return nil
}

type TopologyPort struct {
	VertexId             string        `protobuf:"bytes,1,opt,name=vertex_id,json=vertexId,proto3" json:"vertex_id,omitempty"`
	IfIndex              uint64        `protobuf:"varint,2,opt,name=if_index,json=ifIndex,proto3" json:"if_index,omitempty"`
	IfName               string        `protobuf:"bytes,3,opt,name=if_name,json=ifName,proto3" json:"if_name,omitempty"`
	Address              string        `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	NodeCriteria         *NodeCriteria `protobuf:"bytes,5,opt,name=node_criteria,json=nodeCriteria,proto3" json:"node_criteria,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TopologyPort) Reset()         { *m = TopologyPort{} }
func (m *TopologyPort) String() string { return proto.CompactTextString(m) }
func (*TopologyPort) ProtoMessage()    {}
func (*TopologyPort) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5238ae8b6d75269, []int{12}
}

func (m *TopologyPort) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopologyPort.Unmarshal(m, b)
}
func (m *TopologyPort) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopologyPort.Marshal(b, m, deterministic)
}
func (m *TopologyPort) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopologyPort.Merge(m, src)
}
func (m *TopologyPort) XXX_Size() int {
	return xxx_messageInfo_TopologyPort.Size(m)
}
func (m *TopologyPort) XXX_DiscardUnknown() {
	xxx_messageInfo_TopologyPort.DiscardUnknown(m)
}

var xxx_messageInfo_TopologyPort proto.InternalMessageInfo

func (m *TopologyPort) GetVertexId() string {
	if m != nil {
		return m.VertexId
	}
	return ""
}

func (m *TopologyPort) GetIfIndex() uint64 {
	if m != nil {
		return m.IfIndex
	}
	return 0
}

func (m *TopologyPort) GetIfName() string {
	if m != nil {
		return m.IfName
	}
	return ""
}

func (m *TopologyPort) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *TopologyPort) GetNodeCriteria() *NodeCriteria {
	if m != nil {
		return m.NodeCriteria
	}
	return nil
}

type TopologyEdge struct {
	Ref *TopologyRef `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	// Types that are valid to be assigned to Source:
	//	*TopologyEdge_SourcePort
	//	*TopologyEdge_SourceSegment
	//	*TopologyEdge_SourceNode
	Source isTopologyEdge_Source `protobuf_oneof:"source"`
	// Types that are valid to be assigned to Target:
	//	*TopologyEdge_TargetPort
	//	*TopologyEdge_TargetSegment
	//	*TopologyEdge_TargetNode
	Target               isTopologyEdge_Target `protobuf_oneof:"target"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *TopologyEdge) Reset()         { *m = TopologyEdge{} }
func (m *TopologyEdge) String() string { return proto.CompactTextString(m) }
func (*TopologyEdge) ProtoMessage()    {}
func (*TopologyEdge) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5238ae8b6d75269, []int{13}
}

func (m *TopologyEdge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopologyEdge.Unmarshal(m, b)
}
func (m *TopologyEdge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopologyEdge.Marshal(b, m, deterministic)
}
func (m *TopologyEdge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopologyEdge.Merge(m, src)
}
func (m *TopologyEdge) XXX_Size() int {
	return xxx_messageInfo_TopologyEdge.Size(m)
}
func (m *TopologyEdge) XXX_DiscardUnknown() {
	xxx_messageInfo_TopologyEdge.DiscardUnknown(m)
}

var xxx_messageInfo_TopologyEdge proto.InternalMessageInfo

func (m *TopologyEdge) GetRef() *TopologyRef {
	if m != nil {
		return m.Ref
	}
	return nil
}

type isTopologyEdge_Source interface {
	isTopologyEdge_Source()
}

type TopologyEdge_SourcePort struct {
	SourcePort *TopologyPort `protobuf:"bytes,3,opt,name=sourcePort,proto3,oneof"`
}

type TopologyEdge_SourceSegment struct {
	SourceSegment *TopologySegment `protobuf:"bytes,4,opt,name=sourceSegment,proto3,oneof"`
}

type TopologyEdge_SourceNode struct {
	SourceNode *Node `protobuf:"bytes,5,opt,name=sourceNode,proto3,oneof"`
}

func (*TopologyEdge_SourcePort) isTopologyEdge_Source() {}

func (*TopologyEdge_SourceSegment) isTopologyEdge_Source() {}

func (*TopologyEdge_SourceNode) isTopologyEdge_Source() {}

func (m *TopologyEdge) GetSource() isTopologyEdge_Source {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *TopologyEdge) GetSourcePort() *TopologyPort {
	if x, ok := m.GetSource().(*TopologyEdge_SourcePort); ok {
		return x.SourcePort
	}
	return nil
}

func (m *TopologyEdge) GetSourceSegment() *TopologySegment {
	if x, ok := m.GetSource().(*TopologyEdge_SourceSegment); ok {
		return x.SourceSegment
	}
	return nil
}

func (m *TopologyEdge) GetSourceNode() *Node {
	if x, ok := m.GetSource().(*TopologyEdge_SourceNode); ok {
		return x.SourceNode
	}
	return nil
}

type isTopologyEdge_Target interface {
	isTopologyEdge_Target()
}

type TopologyEdge_TargetPort struct {
	TargetPort *TopologyPort `protobuf:"bytes,6,opt,name=targetPort,proto3,oneof"`
}

type TopologyEdge_TargetSegment struct {
	TargetSegment *TopologySegment `protobuf:"bytes,7,opt,name=targetSegment,proto3,oneof"`
}

type TopologyEdge_TargetNode struct {
	TargetNode *Node `protobuf:"bytes,8,opt,name=targetNode,proto3,oneof"`
}

func (*TopologyEdge_TargetPort) isTopologyEdge_Target() {}

func (*TopologyEdge_TargetSegment) isTopologyEdge_Target() {}

func (*TopologyEdge_TargetNode) isTopologyEdge_Target() {}

func (m *TopologyEdge) GetTarget() isTopologyEdge_Target {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *TopologyEdge) GetTargetPort() *TopologyPort {
	if x, ok := m.GetTarget().(*TopologyEdge_TargetPort); ok {
		return x.TargetPort
	}
	return nil
}

func (m *TopologyEdge) GetTargetSegment() *TopologySegment {
	if x, ok := m.GetTarget().(*TopologyEdge_TargetSegment); ok {
		return x.TargetSegment
	}
	return nil
}

func (m *TopologyEdge) GetTargetNode() *Node {
	if x, ok := m.GetTarget().(*TopologyEdge_TargetNode); ok {
		return x.TargetNode
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TopologyEdge) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TopologyEdge_SourcePort)(nil),
		(*TopologyEdge_SourceSegment)(nil),
		(*TopologyEdge_SourceNode)(nil),
		(*TopologyEdge_TargetPort)(nil),
		(*TopologyEdge_TargetSegment)(nil),
		(*TopologyEdge_TargetNode)(nil),
	}
}

func init() {
	proto.RegisterEnum("Severity", Severity_name, Severity_value)
	proto.RegisterEnum("Alarm_Type", Alarm_Type_name, Alarm_Type_value)
	proto.RegisterEnum("AlarmFeedback_FeedbackType", AlarmFeedback_FeedbackType_name, AlarmFeedback_FeedbackType_value)
	proto.RegisterEnum("IpInterface_PrimaryType", IpInterface_PrimaryType_name, IpInterface_PrimaryType_value)
	proto.RegisterEnum("TopologyRef_Protocol", TopologyRef_Protocol_name, TopologyRef_Protocol_value)
	proto.RegisterType((*NodeCriteria)(nil), "NodeCriteria")
	proto.RegisterType((*EventParameter)(nil), "EventParameter")
	proto.RegisterType((*Event)(nil), "Event")
	proto.RegisterType((*Alarm)(nil), "Alarm")
	proto.RegisterType((*AlarmFeedback)(nil), "AlarmFeedback")
	proto.RegisterType((*IpInterface)(nil), "IpInterface")
	proto.RegisterType((*SnmpInterface)(nil), "SnmpInterface")
	proto.RegisterType((*HwAlias)(nil), "HwAlias")
	proto.RegisterType((*HwEntity)(nil), "HwEntity")
	proto.RegisterType((*Node)(nil), "Node")
	proto.RegisterType((*TopologyRef)(nil), "TopologyRef")
	proto.RegisterType((*TopologySegment)(nil), "TopologySegment")
	proto.RegisterType((*TopologyPort)(nil), "TopologyPort")
	proto.RegisterType((*TopologyEdge)(nil), "TopologyEdge")
}

func init() { proto.RegisterFile("opennms-kafka-producer.proto", fileDescriptor_e5238ae8b6d75269) }

var fileDescriptor_e5238ae8b6d75269 = []byte{
	// 1853 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0xcd, 0x72, 0xdb, 0xc8,
	0x11, 0x16, 0xff, 0xc1, 0xe6, 0x8f, 0xe0, 0xb1, 0xe5, 0x85, 0xe3, 0xdd, 0x58, 0x61, 0xe2, 0xac,
	0xca, 0xb5, 0xa6, 0xcb, 0x72, 0xe5, 0xa7, 0x6a, 0x2f, 0xa1, 0x48, 0xc8, 0x42, 0x56, 0x22, 0x59,
	0x43, 0x7a, 0x5d, 0xc9, 0x05, 0x35, 0x06, 0x06, 0xd4, 0x44, 0x24, 0x80, 0x1a, 0x80, 0xd2, 0xf2,
	0x4d, 0x72, 0xcc, 0x21, 0xd7, 0x9c, 0xf2, 0x20, 0x79, 0x80, 0x5c, 0x73, 0x4a, 0x5e, 0x22, 0x35,
	0x3d, 0x00, 0x09, 0x5a, 0xbb, 0x71, 0x72, 0xc8, 0x6d, 0xba, 0xfb, 0x9b, 0xfe, 0x9f, 0x46, 0x93,
	0xf0, 0x79, 0x14, 0xf3, 0x30, 0x5c, 0x25, 0x2f, 0x6f, 0x58, 0x70, 0xc3, 0x5e, 0xc6, 0x32, 0xf2,
	0xd7, 0x1e, 0x97, 0xfd, 0x58, 0x46, 0x69, 0xd4, 0xf3, 0xa1, 0x3d, 0x8e, 0x7c, 0x3e, 0x94, 0x22,
	0xe5, 0x52, 0x30, 0xd2, 0x85, 0xb2, 0xf0, 0xad, 0xd2, 0x71, 0xe9, 0xa4, 0x4a, 0xcb, 0xc2, 0x27,
	0xcf, 0xa1, 0x1b, 0x44, 0x92, 0x8b, 0x45, 0xe8, 0x26, 0xd1, 0x5a, 0x7a, 0xdc, 0x2a, 0x1f, 0x97,
	0x4e, 0x9a, 0xb4, 0x93, 0x71, 0x67, 0xc8, 0x24, 0x5f, 0x00, 0xe4, 0x30, 0xe1, 0x5b, 0x15, 0x84,
	0x34, 0x33, 0x8e, 0xe3, 0xf7, 0xc6, 0xd0, 0xb5, 0x6f, 0x79, 0x98, 0x4e, 0x99, 0x64, 0x2b, 0x9e,
	0x72, 0x49, 0x08, 0x54, 0x43, 0xb6, 0xe2, 0x68, 0xa9, 0x49, 0xf1, 0x4c, 0x1e, 0x41, 0xed, 0x96,
	0x2d, 0xd7, 0xb9, 0x09, 0x4d, 0x28, 0x64, 0xba, 0x89, 0x79, 0xa6, 0x14, 0xcf, 0xbd, 0x3f, 0x57,
	0xa0, 0x86, 0x0a, 0xef, 0xf9, 0x6b, 0x42, 0x65, 0xcd, 0x45, 0xa6, 0x41, 0x1d, 0x95, 0xd6, 0x25,
	0xfb, 0xc0, 0x97, 0x99, 0x02, 0x4d, 0xa0, 0x56, 0xb1, 0xe2, 0x56, 0x15, 0x6f, 0xe2, 0x99, 0x3c,
	0x86, 0x7a, 0x16, 0x63, 0x0d, 0xa1, 0x19, 0x45, 0x5e, 0x42, 0x33, 0xce, 0x1d, 0xb7, 0xea, 0xc7,
	0x95, 0x93, 0xd6, 0xe9, 0x61, 0x7f, 0x3f, 0x1e, 0xba, 0x43, 0x90, 0x67, 0xd0, 0xf2, 0x24, 0x67,
	0x29, 0x77, 0xd1, 0x42, 0x03, 0x2d, 0x80, 0x66, 0xcd, 0x95, 0x9d, 0x63, 0x68, 0xf9, 0x3c, 0xf1,
	0xa4, 0x88, 0x53, 0x11, 0x85, 0x96, 0x81, 0xc6, 0x8a, 0x2c, 0xa5, 0x62, 0x19, 0x2d, 0xdc, 0x15,
	0x4f, 0x12, 0xb6, 0xe0, 0x56, 0x13, 0x11, 0xb0, 0x8c, 0x16, 0x57, 0x9a, 0x43, 0x9e, 0x83, 0x91,
	0xf0, 0x5b, 0x2e, 0x45, 0xba, 0xb1, 0xe0, 0xb8, 0x74, 0xd2, 0x3d, 0x6d, 0xf6, 0x67, 0x19, 0x83,
	0x6e, 0x45, 0x2a, 0x1b, 0xcb, 0x68, 0x61, 0xb5, 0x8e, 0x4b, 0x27, 0x06, 0x55, 0x47, 0x62, 0x41,
	0xc3, 0x17, 0x49, 0xbc, 0x64, 0x1b, 0xab, 0x8d, 0xdc, 0x9c, 0x24, 0xa7, 0xd0, 0x09, 0x23, 0x9f,
	0xbb, 0x5e, 0xd6, 0x0a, 0x56, 0xe7, 0xb8, 0x74, 0xd2, 0x3a, 0xed, 0xf4, 0x8b, 0xfd, 0x41, 0xdb,
	0x61, 0xb1, 0x5b, 0xbe, 0x00, 0x10, 0xb1, 0xcb, 0x7c, 0x5f, 0xf2, 0x24, 0xb1, 0xba, 0xba, 0xec,
	0x22, 0x1e, 0x68, 0x46, 0xef, 0xef, 0x75, 0xa8, 0x0d, 0x96, 0x4c, 0xae, 0xfe, 0x8b, 0x32, 0xdd,
	0x33, 0x5f, 0xf9, 0x5f, 0xcd, 0x57, 0x3f, 0x32, 0x4f, 0x7e, 0x02, 0xed, 0x84, 0xcb, 0x5b, 0xe1,
	0x71, 0x17, 0x7b, 0x4d, 0x57, 0xb5, 0x95, 0xf1, 0xc6, 0xaa, 0xe5, 0x7e, 0x0a, 0x1d, 0xc9, 0xfd,
	0xb5, 0xa7, 0xb2, 0xee, 0xde, 0xf0, 0x8d, 0x55, 0x47, 0x4c, 0x7b, 0xcb, 0xfc, 0x86, 0x6f, 0xc8,
	0xb3, 0xac, 0x03, 0x1b, 0x98, 0xe8, 0x56, 0x1f, 0x43, 0xea, 0xcf, 0x37, 0x31, 0xd7, 0xed, 0xa8,
	0x5a, 0xcc, 0x8b, 0xd6, 0x61, 0x8a, 0xa5, 0xac, 0x52, 0x4d, 0xec, 0xd5, 0xa8, 0xf9, 0xc3, 0x35,
	0x3a, 0x01, 0x33, 0x10, 0x32, 0x49, 0x5d, 0xae, 0x3a, 0x4a, 0xf7, 0x0c, 0xa0, 0x9e, 0x2e, 0xf2,
	0xb1, 0xd1, 0xbe, 0xaf, 0x6f, 0x5a, 0x9f, 0xec, 0x9b, 0xf6, 0xbd, 0xbe, 0x79, 0x02, 0x06, 0xf3,
	0x6e, 0xdc, 0x75, 0xc2, 0x25, 0xd6, 0xb7, 0x49, 0x1b, 0xcc, 0xbb, 0x79, 0x97, 0x70, 0x99, 0x8b,
	0xd0, 0x7e, 0x17, 0xed, 0x2b, 0x11, 0x1a, 0x7e, 0x0e, 0xb0, 0x64, 0xb9, 0x87, 0xd6, 0x21, 0x16,
	0xa6, 0xae, 0x5f, 0x00, 0x6d, 0x2a, 0x89, 0x7e, 0x8b, 0x3f, 0x87, 0xc3, 0x1d, 0x4c, 0x2b, 0x32,
	0x51, 0x51, 0x67, 0x8b, 0x41, 0x75, 0x4f, 0xc0, 0x10, 0x81, 0x2b, 0x42, 0x9f, 0x7f, 0x67, 0x3d,
	0x38, 0x2e, 0x9d, 0x74, 0x68, 0x43, 0x04, 0x8e, 0x22, 0xc9, 0x1b, 0x38, 0x8a, 0x62, 0x2e, 0x59,
	0x1a, 0x49, 0x57, 0x84, 0x49, 0x2a, 0x75, 0x15, 0x12, 0x8b, 0xa0, 0xb3, 0x8f, 0x72, 0xa1, 0x53,
	0x90, 0x91, 0xa7, 0xd0, 0xf4, 0x96, 0x9c, 0x49, 0x2c, 0xe0, 0x43, 0x04, 0x1a, 0xc8, 0x50, 0xc5,
	0xfb, 0x25, 0x7c, 0xb6, 0x62, 0x21, 0x5b, 0x70, 0xdf, 0x8d, 0x3e, 0xfc, 0x81, 0x7b, 0x29, 0xea,
	0x65, 0xa1, 0xc7, 0xad, 0x47, 0x08, 0x3d, 0xca, 0xc4, 0x13, 0x94, 0x3a, 0x99, 0x90, 0xf4, 0xe1,
	0xe1, 0x47, 0xf7, 0xb0, 0x07, 0x8e, 0xf0, 0xce, 0x83, 0xbd, 0x3b, 0xaa, 0x13, 0xc8, 0x0b, 0x68,
	0x4b, 0xbe, 0x64, 0x29, 0xf7, 0xb1, 0x3d, 0xac, 0xc7, 0x38, 0x27, 0xea, 0xba, 0x59, 0xe8, 0x9e,
	0xac, 0x37, 0x82, 0x2a, 0xde, 0x79, 0x0c, 0x64, 0x4a, 0x27, 0x67, 0x97, 0xf6, 0x95, 0xfb, 0xde,
	0x99, 0x5f, 0xb8, 0xc3, 0x4b, 0x7b, 0x40, 0xcd, 0x03, 0xd2, 0x84, 0x9a, 0x3e, 0x96, 0xc8, 0x13,
	0x38, 0x2a, 0x42, 0x26, 0xef, 0xe6, 0x19, 0xaa, 0xdc, 0xfb, 0x47, 0x19, 0x3a, 0xa8, 0xef, 0x9c,
	0x73, 0xff, 0x03, 0xf3, 0x6e, 0x54, 0x37, 0x27, 0x22, 0x5d, 0xb3, 0x6d, 0x37, 0xeb, 0xe9, 0xda,
	0xde, 0x32, 0x55, 0x42, 0xde, 0xc0, 0xd1, 0x0e, 0x14, 0x88, 0x70, 0xc1, 0x65, 0x2c, 0x45, 0x98,
	0x66, 0x8f, 0xf1, 0xd1, 0x56, 0x78, 0xbe, 0x93, 0xa9, 0x14, 0x33, 0x65, 0x0a, 0xb5, 0xea, 0x41,
	0x6a, 0x20, 0x43, 0x69, 0xfc, 0x0d, 0x74, 0x82, 0xcc, 0x05, 0x9d, 0xa4, 0x2a, 0x76, 0xfb, 0xd3,
	0xfe, 0x9e, 0x77, 0xfd, 0xfc, 0x80, 0x0f, 0xa7, 0x1d, 0x14, 0x28, 0x35, 0x79, 0x25, 0x67, 0x49,
	0x14, 0xe6, 0x93, 0x57, 0x53, 0x6a, 0x4a, 0x63, 0xab, 0xea, 0x57, 0x89, 0x67, 0xf2, 0x39, 0x34,
	0x55, 0x6b, 0x25, 0x29, 0x5b, 0xc5, 0xd9, 0x70, 0xdd, 0x31, 0x7a, 0x53, 0x68, 0x17, 0xed, 0x10,
	0x02, 0xdd, 0xf3, 0xc1, 0xe5, 0xcc, 0x76, 0xa7, 0x93, 0x99, 0x33, 0x77, 0xbe, 0xb5, 0xcd, 0x83,
	0x1d, 0x6f, 0x6c, 0xbf, 0x1d, 0x20, 0xaf, 0x44, 0x5a, 0xd0, 0x18, 0x4e, 0x28, 0xb5, 0x87, 0x73,
	0xb3, 0xac, 0x88, 0x77, 0xe3, 0x6f, 0xc6, 0x93, 0xf7, 0x63, 0xb3, 0xd2, 0xfb, 0x57, 0x09, 0x5a,
	0x4e, 0xec, 0x84, 0x29, 0x97, 0x01, 0xf3, 0xf8, 0xbd, 0x51, 0xb6, 0x3f, 0x84, 0xca, 0x1f, 0x0f,
	0xa1, 0x62, 0xb3, 0x57, 0xf6, 0x9b, 0xfd, 0x6b, 0x68, 0xc7, 0x52, 0xac, 0x98, 0xdc, 0x14, 0xd3,
	0x66, 0xf5, 0x0b, 0xd6, 0xfa, 0x53, 0x0d, 0xc0, 0x9c, 0xb5, 0xe2, 0x1d, 0xa1, 0x06, 0x79, 0x36,
	0xc8, 0xac, 0xda, 0x71, 0x45, 0x3d, 0xe4, 0x8c, 0xec, 0x7d, 0x0d, 0xad, 0xc2, 0x2d, 0x15, 0xcc,
	0x94, 0x3a, 0x57, 0x03, 0xfa, 0x3b, 0xf3, 0x80, 0x74, 0xa0, 0x39, 0xb3, 0x87, 0x93, 0xf1, 0x48,
	0x91, 0x25, 0x62, 0x42, 0x7b, 0x3c, 0x99, 0xbb, 0xf6, 0xa5, 0xf3, 0xd6, 0x39, 0xbb, 0xb4, 0xcd,
	0x72, 0xef, 0xaf, 0x65, 0xe8, 0xcc, 0xc2, 0xd5, 0x7f, 0x88, 0xb7, 0x18, 0x50, 0x79, 0x3f, 0x20,
	0x2d, 0xc2, 0x81, 0x94, 0x35, 0x49, 0x43, 0x04, 0x23, 0x45, 0x92, 0xcf, 0xa0, 0x21, 0x82, 0x5d,
	0x98, 0x1d, 0x5a, 0x17, 0x01, 0xba, 0xa7, 0x05, 0x85, 0xf9, 0x5c, 0x17, 0x01, 0x8e, 0x66, 0xad,
	0x2c, 0x89, 0x39, 0xf7, 0xb1, 0xfe, 0x55, 0xa5, 0x6c, 0xa6, 0x48, 0x35, 0x68, 0x44, 0xe0, 0xc6,
	0xd7, 0x9b, 0x64, 0x9b, 0xf7, 0x86, 0xde, 0x4a, 0x44, 0x30, 0xbd, 0xde, 0x24, 0x79, 0xee, 0x35,
	0x8e, 0xf9, 0x2b, 0x11, 0xba, 0x49, 0xca, 0xd2, 0x75, 0x82, 0x13, 0xba, 0xa3, 0x70, 0x03, 0xc5,
	0x9d, 0x21, 0x93, 0xfc, 0x0c, 0xba, 0x22, 0x70, 0xd5, 0x6c, 0xc9, 0x61, 0x4d, 0x84, 0xb5, 0x45,
	0x30, 0x89, 0xb9, 0xcc, 0x50, 0xda, 0x21, 0xb6, 0x14, 0x2c, 0xc1, 0x01, 0x8d, 0xd1, 0x0d, 0x14,
	0xd9, 0x7b, 0x0d, 0x8d, 0x8b, 0x3b, 0x3c, 0xaa, 0x6f, 0x81, 0xce, 0x4d, 0x09, 0x55, 0x68, 0x42,
	0x7d, 0xef, 0x22, 0xe1, 0xe7, 0xdf, 0xbb, 0x48, 0xf8, 0xbd, 0x3f, 0x56, 0xc0, 0xb8, 0xb8, 0xb3,
	0xc3, 0x54, 0x7d, 0x03, 0xbe, 0x02, 0xa2, 0x46, 0xa6, 0x8a, 0x48, 0x78, 0x6c, 0xe9, 0x16, 0x35,
	0x98, 0x6a, 0xcf, 0xc8, 0x04, 0x3a, 0xcd, 0x4f, 0xa1, 0xc9, 0xf1, 0x9e, 0x9b, 0xa9, 0xec, 0x50,
	0x43, 0x33, 0x1c, 0xff, 0x9e, 0x2a, 0x6f, 0xc9, 0x92, 0x24, 0xab, 0x46, 0x51, 0xd5, 0x50, 0xf1,
	0xef, 0xa1, 0x75, 0xed, 0xaa, 0xf7, 0xd0, 0xba, 0x88, 0x2f, 0xe1, 0xe1, 0xbe, 0x9b, 0x89, 0x1b,
	0xc8, 0x35, 0xd6, 0xcd, 0xd8, 0xf7, 0x33, 0x39, 0x97, 0x6b, 0xf2, 0x02, 0x1e, 0xec, 0xc1, 0xb1,
	0xc8, 0xfa, 0x29, 0x1f, 0x16, 0xc0, 0x58, 0xed, 0x5f, 0x81, 0xb5, 0x87, 0xbd, 0xe5, 0xa1, 0x1f,
	0x49, 0x77, 0xfb, 0xdd, 0x6d, 0xd2, 0xa3, 0xc2, 0x95, 0x6f, 0x51, 0x9a, 0xcf, 0x5d, 0x75, 0xf1,
	0xfa, 0x2e, 0xab, 0x8c, 0x81, 0x73, 0xd7, 0xe8, 0x67, 0xf5, 0xa0, 0xc0, 0xc3, 0x34, 0xaf, 0xcd,
	0x73, 0x30, 0xbc, 0x6b, 0xb1, 0xf4, 0x25, 0x0f, 0xad, 0x26, 0xe2, 0x9a, 0xfd, 0xbc, 0x06, 0x74,
	0x2b, 0xea, 0xfd, 0xad, 0x02, 0x55, 0xb5, 0x75, 0xfc, 0x7f, 0x96, 0x61, 0xf2, 0x23, 0x30, 0x96,
	0x91, 0x87, 0x23, 0x36, 0xcb, 0xf4, 0x96, 0x56, 0x32, 0x8f, 0xa5, 0x7c, 0x11, 0xc9, 0x4d, 0xf6,
	0xac, 0xb7, 0xf4, 0x6e, 0x91, 0xad, 0x17, 0x17, 0xd9, 0x4f, 0x6e, 0x9b, 0xcf, 0xa0, 0x95, 0x6c,
	0x12, 0xd7, 0x8b, 0xc2, 0x94, 0x79, 0x69, 0xb6, 0x6d, 0x42, 0xb2, 0x49, 0x86, 0x9a, 0x43, 0xbe,
	0x84, 0x43, 0x05, 0x28, 0xae, 0x16, 0x7a, 0xe1, 0xec, 0x26, 0x9b, 0x64, 0x54, 0xd8, 0x2e, 0x7a,
	0xd0, 0x51, 0xc0, 0xfc, 0x33, 0xea, 0x67, 0xaf, 0x40, 0xa9, 0xcf, 0x3e, 0x9e, 0x3e, 0x79, 0x05,
	0x6d, 0x11, 0xbb, 0x22, 0x9f, 0x1e, 0x56, 0x0b, 0xd3, 0xdc, 0x2e, 0xce, 0x34, 0xda, 0x12, 0x85,
	0xf1, 0xf2, 0x0b, 0xe8, 0x26, 0xe1, 0xaa, 0x78, 0xa5, 0x8d, 0x57, 0xba, 0xfd, 0xbd, 0x31, 0x44,
	0x3b, 0xc9, 0xde, 0x54, 0xfa, 0x0a, 0xda, 0xd7, 0x77, 0xae, 0x08, 0xd5, 0x52, 0xa1, 0x92, 0xa5,
	0x97, 0xd5, 0x42, 0x39, 0x5b, 0xd7, 0x77, 0x4e, 0x2e, 0xed, 0xfd, 0xa9, 0x04, 0xad, 0x79, 0x14,
	0x47, 0xcb, 0x68, 0xb1, 0xa1, 0x3c, 0x28, 0x14, 0xb6, 0x89, 0x85, 0x7d, 0x0d, 0x06, 0xfe, 0x1c,
	0xf2, 0xa2, 0x25, 0x96, 0xb4, 0x7b, 0x7a, 0xd4, 0x2f, 0xe0, 0xfb, 0xd3, 0x4c, 0x48, 0xb7, 0xb0,
	0xde, 0x18, 0x8c, 0x9c, 0x4b, 0x0c, 0xa8, 0x5e, 0x5e, 0x8e, 0xa6, 0xe6, 0x81, 0x3a, 0x4d, 0x66,
	0xd3, 0x73, 0xb3, 0xa4, 0x4e, 0xce, 0xcc, 0x99, 0x99, 0x65, 0x02, 0x50, 0x3f, 0xa3, 0xce, 0xe8,
	0xad, 0x6d, 0x56, 0x48, 0x03, 0x2a, 0xc3, 0xd1, 0xd4, 0xac, 0x92, 0x43, 0x68, 0xbd, 0x9b, 0xd9,
	0x74, 0x64, 0x9f, 0x3b, 0x63, 0x7b, 0x64, 0xd6, 0x7a, 0xaf, 0xe1, 0x30, 0xb7, 0x38, 0xe3, 0x8b,
	0x95, 0xda, 0xa7, 0x7e, 0x0c, 0x15, 0xc9, 0x03, 0x74, 0x53, 0xa5, 0xb0, 0xe0, 0x10, 0x55, 0x82,
	0xde, 0x5f, 0x4a, 0xd0, 0xce, 0x99, 0xd3, 0x48, 0xe2, 0x57, 0xfa, 0x96, 0xcb, 0x94, 0x7f, 0xe7,
	0x6e, 0xa3, 0x33, 0x34, 0xc3, 0xb9, 0x3f, 0xb7, 0xab, 0xbb, 0xb9, 0x5d, 0x98, 0xc1, 0x95, 0xbd,
	0x19, 0x6c, 0x41, 0x63, 0x7f, 0xbb, 0xce, 0xc9, 0xfb, 0xeb, 0x7a, 0xed, 0x93, 0xeb, 0x7a, 0xef,
	0x9f, 0xe5, 0x9d, 0xbf, 0xb6, 0xbf, 0xe0, 0x9f, 0x0a, 0x90, 0xbc, 0x02, 0xd0, 0xef, 0x4c, 0x45,
	0xb7, 0xfd, 0x41, 0x50, 0x0c, 0xf9, 0xe2, 0x80, 0x16, 0x20, 0xe4, 0xd7, 0xd0, 0xd1, 0x54, 0x96,
	0x42, 0xf4, 0xba, 0x75, 0x6a, 0xf6, 0x3f, 0x4a, 0xed, 0xc5, 0x01, 0xdd, 0x07, 0x92, 0x2f, 0x73,
	0x53, 0xca, 0xff, 0x2c, 0x98, 0x1a, 0x06, 0xb3, 0x33, 0x81, 0x33, 0xe1, 0x15, 0x40, 0xca, 0xe4,
	0x82, 0xa7, 0xe8, 0x53, 0xfd, 0xfb, 0x7c, 0x2a, 0xd1, 0x02, 0x44, 0xf9, 0xa4, 0xa9, 0xdc, 0xa7,
	0xc6, 0x0f, 0xf8, 0x54, 0xa2, 0xfb, 0x40, 0xe5, 0x93, 0x66, 0xa0, 0x4f, 0x46, 0xd1, 0xa7, 0xad,
	0x09, 0x45, 0x9d, 0x19, 0xf9, 0x0f, 0x57, 0x75, 0xd2, 0xfc, 0x17, 0x0b, 0x30, 0xf2, 0x1f, 0x1b,
	0xe4, 0x01, 0x74, 0x9c, 0xf1, 0xc8, 0x9e, 0xdb, 0xf4, 0xca, 0x19, 0x0f, 0xe6, 0x6a, 0x07, 0x52,
	0xfb, 0x8e, 0xda, 0x23, 0xed, 0x91, 0x59, 0x52, 0x1d, 0x3a, 0x9e, 0xd0, 0xab, 0xc1, 0xa5, 0xde,
	0x7d, 0xde, 0x0f, 0xe8, 0xd8, 0x19, 0xbf, 0x35, 0x2b, 0x6a, 0x11, 0xbd, 0x72, 0xc6, 0x13, 0x6a,
	0x56, 0xf1, 0x38, 0xf8, 0xed, 0x84, 0x9a, 0x35, 0xd2, 0x06, 0x63, 0x48, 0x9d, 0xb9, 0x33, 0x1c,
	0x5c, 0x9a, 0xf5, 0x33, 0xf8, 0xbd, 0x91, 0xff, 0xa7, 0xf0, 0xa1, 0x8e, 0xcf, 0xe3, 0xcd, 0xbf,
	0x03, 0x00, 0x00, 0xff, 0xff, 0x31, 0x52, 0xed, 0x2d, 0x74, 0x10, 0x00, 0x00,
}
