# @author Alejandro Galue <agalue@opennms.org>

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zk
spec:
  template:
    spec:
      containers:
      - name: zk
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 256Mi
          $patch: replace
